// Page components exports
export { default as UserPortalLayout } from './UserPortalLayout'
export { default as AdminPortalSettings } from './AdminPortalSettings'
export { default as AnalystCockpit } from './AnalystCockpit'
export { default as TicketManagementDashboard } from './TicketManagementDashboard'
export { default as WorkspaceLayout } from './WorkspaceLayout'
export { default as TicketChat } from './TicketChat'
export { default as ServiceCatalog } from './ServiceCatalog'
export { default as SlaEventTimeline } from './SlaEventTimeline'
export { default as SettingsGovernance } from './SettingsGovernance'
export { default as WorkflowBuilder } from './WorkflowBuilder'
export { default as ChangeManagementDashboard } from './ChangeManagementDashboard'
export { default as ApprovalInbox } from './ApprovalInbox'
export type { WorkspaceTicket, CompanyLite } from './workspace.types'
